aws:
  access_key_id: sejin.yun
  secret_access_key: 12345
  bucket_name: bucket_llm

paths:
  local_path: c:/workplace/airflow/llm
  extract_path: c:/workplace/airflow/llm/extract/files

database:
  host: localhost
  database: your_database_name
  user: your_username
  password: your_password